# Generated by Django 3.2.6 on 2021-08-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typesubscription',
            name='duration',
            field=models.CharField(choices=[('Год', 'Год'), ('Пол', 'Полгода'), ('Мес', 'Месяц'), ('Ден', 'День')], default='Год', max_length=3, verbose_name='Время действия'),
        ),
    ]
