# Generated by Django 3.2.6 on 2021-08-10 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_auto_20210810_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='duration',
        ),
    ]
