# Generated by Django 3.2.6 on 2021-08-15 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_alter_subscription_startuse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['recordStartData'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='recordStart',
        ),
        migrations.AddField(
            model_name='schedule',
            name='recordStartData',
            field=models.DateField(default=datetime.datetime(2016, 11, 1, 7, 15, 12, 655838), verbose_name='Дата занятия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='recordStartTime',
            field=models.TimeField(default=datetime.datetime(2021, 8, 15, 12, 23, 26, 997128, tzinfo=utc), verbose_name='Время занятия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='recordTime',
            field=models.CharField(choices=[('Ч', 'Час'), ('П', 'Пол часа'), ('Д', 'Два часа')], max_length=1, verbose_name='Продолжительность'),
        ),
    ]
